version: "3"

services:
  crypto-trading:
    image: 302142484185.dkr.ecr.eu-west-2.amazonaws.com/binance-trade-bot:latest
    container_name: binance_trader
    working_dir: /app
    volumes:
      - data:/app/data
      # - logs:/app/logs
    command: python -m binance_trade_bot
    environment:
      - PYTHONUNBUFFERED=1

  # api:
  #   image: 302142484185.dkr.ecr.eu-west-2.amazonaws.com/binance-trade-bot:latest
  #   container_name: binance_trader_api
  #   working_dir: /app
  #   volumes:
  #     - data:/app/data
  #     - logs:/app/logs
    # ports:
    #   - target: 5123
    #     x-aws-protocol: http
    # command: gunicorn binance_trade_bot.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123
    # depends_on:
    #   - crypto-trading

  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - data:/data
    # ports:
    #   - 3000:3000

volumes: 
  data:
  # logs:
  